package model.dbmodel;

import model.base.Base inflowXajt;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class  inflowXajt extends Base inflowXajt< inflowXajt> {
	public static final  inflowXajt dao = new  inflowXajt().dao();
}
