package model.dbmodel;

import model.base.BaseAreaDis;

import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AreaDis extends BaseAreaDis<AreaDis> {
	public static final AreaDis dao = new AreaDis().dao();

}
