package model.dbmodel;

import model.base.BaseCfBb;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CfBb extends BaseCfBb<CfBb> {
	public static final CfBb dao = new CfBb().dao();
}
