package model.dbmodel;

import model.base.BaseCfR;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CfR extends BaseCfR<CfR> {
	public static final CfR dao = new CfR().dao();
}
