package model.dbmodel;

import model.base.BaseCfT;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CfT extends BaseCfT<CfT> {
	public static final CfT dao = new CfT().dao();
}
