package model.dbmodel;

import model.base.BaseCtrCt;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CtrCt extends BaseCtrCt<CtrCt> {
	public static final CtrCt dao = new CtrCt().dao();
}
