package model.dbmodel;

import model.base.BaseCtrOtq;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CtrOtq extends BaseCtrOtq<CtrOtq> {
	public static final CtrOtq dao = new CtrOtq().dao();
}
