package model.dbmodel;

import model.base.BaseCtrR;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CtrR extends BaseCtrR<CtrR> {
	public static final CtrR dao = new CtrR().dao();
}
