package model.dbmodel;

import model.base.BaseCurveHs;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CurveHs extends BaseCurveHs<CurveHs> {
	public static final CurveHs dao = new CurveHs().dao();
}
