package model.dbmodel;

import model.base.BaseDataC;

import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DataC extends BaseDataC<DataC> {
	public static final DataC dao = new DataC().dao();
}
