package model.dbmodel;

import model.base.BaseDatasCf;

import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DatasCf extends BaseDatasCf<DatasCf> {
	public static final DatasCf dao = new DatasCf().dao();
}
