package model.dbmodel;

import model.base.BaseDatasLt;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DatasLt extends BaseDatasLt<DatasLt> {
	public static final DatasLt dao = new DatasLt().dao();
}
