package model.dbmodel;

import model.base.BaseDatasM;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DatasM extends BaseDatasM<DatasM> {
	public static final DatasM dao = new DatasM().dao();
}
