package model.dbmodel;

import model.base.BaseDatasU;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DatasU extends BaseDatasU<DatasU> {
	public static final DatasU dao = new DatasU().dao();
}
