package model.dbmodel;

import model.base.BaseDayevH;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DayevH extends BaseDayevH<DayevH> {
	public static final DayevH dao = new DayevH().dao();
}
