package model.dbmodel;

import model.base.BaseDayrnflF;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DayrnflF extends BaseDayrnflF<DayrnflF> {
	public static final DayrnflF dao = new DayrnflF().dao();
}
