package model.dbmodel;

import model.base.BaseDayrnflH;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DayrnflH extends BaseDayrnflH<DayrnflH> {
	public static final DayrnflH dao = new DayrnflH().dao();
}
