package model.dbmodel;

import model.base.BaseDayrnflCh;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DayrnflCh extends BaseDayrnflCh<DayrnflCh> {
	public static final DayrnflCh dao = new DayrnflCh().dao();
}
