package model.dbmodel;

import model.base.BaseDayrnflAvg;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DayrnflAvg extends BaseDayrnflAvg<DayrnflAvg> {
	public static final DayrnflAvg dao = new DayrnflAvg().dao();
}
