package model.dbmodel;

import model.base.BaseEventFe;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class EventFe extends BaseEventFe<EventFe> {
	public static final EventFe dao = new EventFe().dao();
}
