package model.dbmodel;

import model.base.BaseForecastJyr;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ForecastJyr extends BaseForecastJyr<ForecastJyr> {
	public static final ForecastJyr dao = new ForecastJyr().dao();
}
