package model.dbmodel;

import model.base.BaseForecastJyt;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ForecastJyt extends BaseForecastJyt<ForecastJyt> {
	public static final ForecastJyt dao = new ForecastJyt().dao();
}
