package model.dbmodel;

import model.base.BaseForecastC;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ForecastC extends BaseForecastC<ForecastC> {
	public static final ForecastC dao = new ForecastC().dao();
}
