package model.dbmodel;

import model.base.BaseForecastXajt;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ForecastXajt extends BaseForecastXajt<ForecastXajt> {
	public static final ForecastXajt dao = new ForecastXajt().dao();
}
