package model.dbmodel;

import model.base.BaseForecastXajr;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ForecastXajr extends BaseForecastXajr<ForecastXajr> {
	public static final ForecastXajr dao = new ForecastXajr().dao();
}
