package model.dbmodel;

import model.base.BaseInflowXajt;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class InflowXajt extends BaseInflowXajt<InflowXajt> {
	public static final InflowXajt dao = new InflowXajt().dao();
}
