package model.dbmodel;

import model.base.BaseInflowXajr;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class InflowXajr extends BaseInflowXajr<InflowXajr> {
	public static final InflowXajr dao = new InflowXajr().dao();
}
