package model.dbmodel;

import model.base.BaseMaterialC;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MaterialC extends BaseMaterialC<MaterialC> {
	public static final MaterialC dao = new MaterialC().dao();
}
