package model.dbmodel;

import model.base.BaseMMusk;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MMusk extends BaseMMusk<MMusk> {
	public static final MMusk dao = new MMusk().dao();
}
