package model.dbmodel;

import model.base.BaseParaM;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ParaM extends BaseParaM<ParaM> {
	public static final ParaM dao = new ParaM().dao();
}
