package model.dbmodel;

import model.base.BaseParaMu;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ParaMu extends BaseParaMu<ParaMu> {
	public static final ParaMu dao = new ParaMu().dao();
}
