package model.dbmodel;

import model.base.BaseRcmR;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class RcmR extends BaseRcmR<RcmR> {
	public static final RcmR dao = new RcmR().dao();
}
