package model.dbmodel;

import model.base.BaseRfnlHr;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class RfnlHr extends BaseRfnlHr<RfnlHr> {
	public static final RfnlHr dao = new RfnlHr().dao();
}
