package model.dbmodel;

import model.base.BaseRiverH;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class RiverH extends BaseRiverH<RiverH> {
	public static final RiverH dao = new RiverH().dao();
}
