package model.dbmodel;

import model.base.BaseRnflF;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class RnflF extends BaseRnflF<RnflF> {
	public static final RnflF dao = new RnflF().dao();
}
