package model.dbmodel;

import model.base.BaseRpCr;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class RpCr extends BaseRpCr<RpCr> {
	public static final RpCr dao = new RpCr().dao();
}
