package model.dbmodel;

import model.base.BaseRpR;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class RpR extends BaseRpR<RpR> {
	public static final RpR dao = new RpR().dao();
}
