package model.dbmodel;

import model.base.BaseRsvrFotq;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class RsvrFotq extends BaseRsvrFotq<RsvrFotq> {
	public static final RsvrFotq dao = new RsvrFotq().dao();
}
