package model.dbmodel;

import model.base.BaseRsvrOtq;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class RsvrOtq extends BaseRsvrOtq<RsvrOtq> {
	public static final RsvrOtq dao = new RsvrOtq().dao();
}
