package model.dbmodel;

import model.base.BaseRsvrC;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class RsvrC extends BaseRsvrC<RsvrC> {
	public static final RsvrC dao = new RsvrC().dao();
}
