package model.dbmodel;

import model.base.BaseSoilW;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SoilW extends BaseSoilW<SoilW> {
	public static final SoilW dao = new SoilW().dao();
}
