package model.dbmodel;

import model.base.BaseSoilH;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SoilH extends BaseSoilH<SoilH> {
	public static final SoilH dao = new SoilH().dao();
}
