package model.dbmodel;

import model.base.BaseSoilCh;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SoilCh extends BaseSoilCh<SoilCh> {
	public static final SoilCh dao = new SoilCh().dao();
}
