package model.dbmodel;

import model.base.BaseStCm;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class StCm extends BaseStCm<StCm> {
	public static final StCm dao = new StCm().dao();
}
