package model.dbmodel;

import model.base.BaseStDis;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class StDis extends BaseStDis<StDis> {
	public static final StDis dao = new StDis().dao();
}
