package model.dbmodel;

import model.base.BaseSysCh;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysCh extends BaseSysCh<SysCh> {
	public static final SysCh dao = new SysCh().dao();
}
