package model.dbmodel;

import model.base.BaseTqR;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TqR extends BaseTqR<TqR> {
	public static final TqR dao = new TqR().dao();
}
