package model.dbmodel;

import model.base.BaseTree;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Tree extends BaseTree<Tree> {
	public static final Tree dao = new Tree().dao();
}
