package model.dbmodel;

import model.base.BaseUhB;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UhB extends BaseUhB<UhB> {
	public static final UhB dao = new UhB().dao();
}
