package model.dbmodel;

import model.base.BaseViewS;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ViewS extends BaseViewS<ViewS> {
	public static final ViewS dao = new ViewS().dao();
}
