package model.dbmodel;

import model.base.BaseWasR;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WasR extends BaseWasR<WasR> {
	public static final WasR dao = new WasR().dao();
}
