package model.dbmodel;

import model.base.BaseXlqxB;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class XlqxB extends BaseXlqxB<XlqxB> {
	public static final XlqxB dao = new XlqxB().dao();
}
