package model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseRcmR<M extends BaseRcmR<M>> extends Model<M> implements IBean {

	public M setNO(java.lang.String NO) {
		set("NO", NO);
		return (M)this;
	}
	
	public java.lang.String getNO() {
		return getStr("NO");
	}

	public M setYMDHM(java.util.Date YMDHM) {
		set("YMDHM", YMDHM);
		return (M)this;
	}
	
	public java.util.Date getYMDHM() {
		return get("YMDHM");
	}

	public M setYMC(java.lang.Integer YMC) {
		set("YMC", YMC);
		return (M)this;
	}
	
	public java.lang.Integer getYMC() {
		return getInt("YMC");
	}

	public M setEHZQ(java.math.BigDecimal EHZQ) {
		set("EHZQ", EHZQ);
		return (M)this;
	}
	
	public java.math.BigDecimal getEHZQ() {
		return get("EHZQ");
	}

	public M setSHZQ(java.math.BigDecimal SHZQ) {
		set("SHZQ", SHZQ);
		return (M)this;
	}
	
	public java.math.BigDecimal getSHZQ() {
		return get("SHZQ");
	}

	public M setGLZQ(java.math.BigDecimal GLZQ) {
		set("GLZQ", GLZQ);
		return (M)this;
	}
	
	public java.math.BigDecimal getGLZQ() {
		return get("GLZQ");
	}

	public M setGLDZQ(java.math.BigDecimal GLDZQ) {
		set("GLDZQ", GLDZQ);
		return (M)this;
	}
	
	public java.math.BigDecimal getGLDZQ() {
		return get("GLDZQ");
	}

	public M setEHZQXL(java.math.BigDecimal EHZQXL) {
		set("EHZQXL", EHZQXL);
		return (M)this;
	}
	
	public java.math.BigDecimal getEHZQXL() {
		return get("EHZQXL");
	}

	public M setSHZQXL(java.math.BigDecimal SHZQXL) {
		set("SHZQXL", SHZQXL);
		return (M)this;
	}
	
	public java.math.BigDecimal getSHZQXL() {
		return get("SHZQXL");
	}

	public M setGLZQXL(java.math.BigDecimal GLZQXL) {
		set("GLZQXL", GLZQXL);
		return (M)this;
	}
	
	public java.math.BigDecimal getGLZQXL() {
		return get("GLZQXL");
	}

}
