package model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseStCm<M extends BaseStCm<M>> extends Model<M> implements IBean {

	public M setID(java.lang.String ID) {
		set("ID", ID);
		return (M)this;
	}
	
	public java.lang.String getID() {
		return getStr("ID");
	}

	public M setSTCD(java.lang.String STCD) {
		set("STCD", STCD);
		return (M)this;
	}
	
	public java.lang.String getSTCD() {
		return getStr("STCD");
	}

	public M setBSNM(java.lang.String BSNM) {
		set("BSNM", BSNM);
		return (M)this;
	}
	
	public java.lang.String getBSNM() {
		return getStr("BSNM");
	}

}
