package model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseSoilW<M extends BaseSoilW<M>> extends Model<M> implements IBean {

	public M setDMCD(java.lang.String DMCD) {
		set("DMCD", DMCD);
		return (M)this;
	}
	
	public java.lang.String getDMCD() {
		return getStr("DMCD");
	}

	public M setARCD(java.lang.String ARCD) {
		set("ARCD", ARCD);
		return (M)this;
	}
	
	public java.lang.String getARCD() {
		return getStr("ARCD");
	}

	public M setNO(java.lang.String NO) {
		set("NO", NO);
		return (M)this;
	}
	
	public java.lang.String getNO() {
		return getStr("NO");
	}

	public M setYMDHM(java.util.Date YMDHM) {
		set("YMDHM", YMDHM);
		return (M)this;
	}
	
	public java.util.Date getYMDHM() {
		return get("YMDHM");
	}

	public M setYMC(java.lang.Integer YMC) {
		set("YMC", YMC);
		return (M)this;
	}
	
	public java.lang.Integer getYMC() {
		return getInt("YMC");
	}

	public M setE(java.math.BigDecimal e) {
		set("e", e);
		return (M)this;
	}
	
	public java.math.BigDecimal getE() {
		return get("e");
	}

	public M setP(java.math.BigDecimal p) {
		set("p", p);
		return (M)this;
	}
	
	public java.math.BigDecimal getP() {
		return get("p");
	}

	public M setW(java.math.BigDecimal w) {
		set("w", w);
		return (M)this;
	}
	
	public java.math.BigDecimal getW() {
		return get("w");
	}

	public M setWu(java.math.BigDecimal wu) {
		set("wu", wu);
		return (M)this;
	}
	
	public java.math.BigDecimal getWu() {
		return get("wu");
	}

	public M setWl(java.math.BigDecimal wl) {
		set("wl", wl);
		return (M)this;
	}
	
	public java.math.BigDecimal getWl() {
		return get("wl");
	}

	public M setWd(java.math.BigDecimal wd) {
		set("wd", wd);
		return (M)this;
	}
	
	public java.math.BigDecimal getWd() {
		return get("wd");
	}

	public M setQ(java.math.BigDecimal q) {
		set("q", q);
		return (M)this;
	}
	
	public java.math.BigDecimal getQ() {
		return get("q");
	}

	public M setS(java.math.BigDecimal s) {
		set("s", s);
		return (M)this;
	}
	
	public java.math.BigDecimal getS() {
		return get("s");
	}

	public M setFr(java.math.BigDecimal fr) {
		set("fr", fr);
		return (M)this;
	}
	
	public java.math.BigDecimal getFr() {
		return get("fr");
	}

}
