package model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseDatasCf<M extends BaseDatasCf<M>> extends Model<M> implements IBean {

	public M setDS(java.lang.Integer DS) {
		set("DS", DS);
		return (M)this;
	}
	
	public java.lang.Integer getDS() {
		return getInt("DS");
	}

	public M setDSN(java.lang.String DSN) {
		set("DSN", DSN);
		return (M)this;
	}
	
	public java.lang.String getDSN() {
		return getStr("DSN");
	}

	public M setDBN(java.lang.String DBN) {
		set("DBN", DBN);
		return (M)this;
	}
	
	public java.lang.String getDBN() {
		return getStr("DBN");
	}

	public M setPOT(java.lang.String POT) {
		set("POT", POT);
		return (M)this;
	}
	
	public java.lang.String getPOT() {
		return getStr("POT");
	}

	public M setURL(java.lang.String URL) {
		set("URL", URL);
		return (M)this;
	}
	
	public java.lang.String getURL() {
		return getStr("URL");
	}

	public M setUSRN(java.lang.String USRN) {
		set("USRN", USRN);
		return (M)this;
	}
	
	public java.lang.String getUSRN() {
		return getStr("USRN");
	}

	public M setPSW(java.lang.String PSW) {
		set("PSW", PSW);
		return (M)this;
	}
	
	public java.lang.String getPSW() {
		return getStr("PSW");
	}

	public M setTYP(java.lang.Integer TYP) {
		set("TYP", TYP);
		return (M)this;
	}
	
	public java.lang.Integer getTYP() {
		return getInt("TYP");
	}

}
