package model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseForecastXajt<M extends BaseForecastXajt<M>> extends Model<M> implements IBean {

	public M setNO(java.lang.String NO) {
		set("NO", NO);
		return (M)this;
	}
	
	public java.lang.String getNO() {
		return getStr("NO");
	}

	public M setID(java.lang.String ID) {
		set("ID", ID);
		return (M)this;
	}
	
	public java.lang.String getID() {
		return getStr("ID");
	}

	public M setP(java.math.BigDecimal P) {
		set("P", P);
		return (M)this;
	}
	
	public java.math.BigDecimal getP() {
		return get("P");
	}

	public M setW(java.math.BigDecimal W) {
		set("W", W);
		return (M)this;
	}
	
	public java.math.BigDecimal getW() {
		return get("W");
	}

	public M setPW(java.math.BigDecimal PW) {
		set("PW", PW);
		return (M)this;
	}
	
	public java.math.BigDecimal getPW() {
		return get("PW");
	}

	public M setOBW(java.math.BigDecimal OBW) {
		set("OBW", OBW);
		return (M)this;
	}
	
	public java.math.BigDecimal getOBW() {
		return get("OBW");
	}

	public M setDW(java.math.BigDecimal DW) {
		set("DW", DW);
		return (M)this;
	}
	
	public java.math.BigDecimal getDW() {
		return get("DW");
	}

	public M setWE(java.math.BigDecimal WE) {
		set("WE", WE);
		return (M)this;
	}
	
	public java.math.BigDecimal getWE() {
		return get("WE");
	}

	public M setOBPD(java.math.BigDecimal OBPD) {
		set("OBPD", OBPD);
		return (M)this;
	}
	
	public java.math.BigDecimal getOBPD() {
		return get("OBPD");
	}

	public M setFOPD(java.math.BigDecimal FOPD) {
		set("FOPD", FOPD);
		return (M)this;
	}
	
	public java.math.BigDecimal getFOPD() {
		return get("FOPD");
	}

	public M setRPE(java.math.BigDecimal RPE) {
		set("RPE", RPE);
		return (M)this;
	}
	
	public java.math.BigDecimal getRPE() {
		return get("RPE");
	}

	public M setOBPT(java.util.Date OBPT) {
		set("OBPT", OBPT);
		return (M)this;
	}
	
	public java.util.Date getOBPT() {
		return get("OBPT");
	}

	public M setFOPT(java.util.Date FOPT) {
		set("FOPT", FOPT);
		return (M)this;
	}
	
	public java.util.Date getFOPT() {
		return get("FOPT");
	}

	public M setFOPZ(java.math.BigDecimal FOPZ) {
		set("FOPZ", FOPZ);
		return (M)this;
	}
	
	public java.math.BigDecimal getFOPZ() {
		return get("FOPZ");
	}

	public M setDY(java.math.BigDecimal DY) {
		set("DY", DY);
		return (M)this;
	}
	
	public java.math.BigDecimal getDY() {
		return get("DY");
	}

}
