package model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseDatasM<M extends BaseDatasM<M>> extends Model<M> implements IBean {

	public M setDS(java.lang.Integer DS) {
		set("DS", DS);
		return (M)this;
	}
	
	public java.lang.Integer getDS() {
		return getInt("DS");
	}

	public M setTID(java.lang.String TID) {
		set("TID", TID);
		return (M)this;
	}
	
	public java.lang.String getTID() {
		return getStr("TID");
	}

	public M setTNM(java.lang.String TNM) {
		set("TNM", TNM);
		return (M)this;
	}
	
	public java.lang.String getTNM() {
		return getStr("TNM");
	}

}
