package model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseForecastC<M extends BaseForecastC<M>> extends Model<M> implements IBean {

	public M setNO(java.lang.String NO) {
		set("NO", NO);
		return (M)this;
	}
	
	public java.lang.String getNO() {
		return getStr("NO");
	}

	public M setBASEDTM(java.util.Date BASEDTM) {
		set("BASEDTM", BASEDTM);
		return (M)this;
	}
	
	public java.util.Date getBASEDTM() {
		return get("BASEDTM");
	}

	public M setSTARTTM(java.util.Date STARTTM) {
		set("STARTTM", STARTTM);
		return (M)this;
	}
	
	public java.util.Date getSTARTTM() {
		return get("STARTTM");
	}

	public M setENDTM(java.util.Date ENDTM) {
		set("ENDTM", ENDTM);
		return (M)this;
	}
	
	public java.util.Date getENDTM() {
		return get("ENDTM");
	}

	public M setWUTM(java.util.Date WUTM) {
		set("WUTM", WUTM);
		return (M)this;
	}
	
	public java.util.Date getWUTM() {
		return get("WUTM");
	}

	public M setYMC1(java.lang.Integer YMC1) {
		set("YMC1", YMC1);
		return (M)this;
	}
	
	public java.lang.Integer getYMC1() {
		return getInt("YMC1");
	}

	public M setYMC2(java.lang.Integer YMC2) {
		set("YMC2", YMC2);
		return (M)this;
	}
	
	public java.lang.Integer getYMC2() {
		return getInt("YMC2");
	}

	public M setYMC3(java.lang.Integer YMC3) {
		set("YMC3", YMC3);
		return (M)this;
	}
	
	public java.lang.Integer getYMC3() {
		return getInt("YMC3");
	}

	public M setYMC4(java.lang.Integer YMC4) {
		set("YMC4", YMC4);
		return (M)this;
	}
	
	public java.lang.Integer getYMC4() {
		return getInt("YMC4");
	}

	public M setE(java.math.BigDecimal E) {
		set("E", E);
		return (M)this;
	}
	
	public java.math.BigDecimal getE() {
		return get("E");
	}

	public M setWE(java.math.BigDecimal WE) {
		set("WE", WE);
		return (M)this;
	}
	
	public java.math.BigDecimal getWE() {
		return get("WE");
	}

	public M setQ(java.math.BigDecimal Q) {
		set("Q", Q);
		return (M)this;
	}
	
	public java.math.BigDecimal getQ() {
		return get("Q");
	}

	public M setZ(java.math.BigDecimal Z) {
		set("Z", Z);
		return (M)this;
	}
	
	public java.math.BigDecimal getZ() {
		return get("Z");
	}

	public M setFL(java.lang.Integer FL) {
		set("FL", FL);
		return (M)this;
	}
	
	public java.lang.Integer getFL() {
		return getInt("FL");
	}

	public M setTLQ(java.math.BigDecimal TLQ) {
		set("TLQ", TLQ);
		return (M)this;
	}
	
	public java.math.BigDecimal getTLQ() {
		return get("TLQ");
	}

	public M setHLQ(java.math.BigDecimal HLQ) {
		set("HLQ", HLQ);
		return (M)this;
	}
	
	public java.math.BigDecimal getHLQ() {
		return get("HLQ");
	}

	public M setELQ(java.math.BigDecimal ELQ) {
		set("ELQ", ELQ);
		return (M)this;
	}
	
	public java.math.BigDecimal getELQ() {
		return get("ELQ");
	}

	public M setSTZ(java.math.BigDecimal STZ) {
		set("STZ", STZ);
		return (M)this;
	}
	
	public java.math.BigDecimal getSTZ() {
		return get("STZ");
	}

	public M setFLD(java.lang.Integer FLD) {
		set("FLD", FLD);
		return (M)this;
	}
	
	public java.lang.Integer getFLD() {
		return getInt("FLD");
	}

	public M setAUTF(java.lang.Integer AUTF) {
		set("AUTF", AUTF);
		return (M)this;
	}
	
	public java.lang.Integer getAUTF() {
		return getInt("AUTF");
	}

}
