package model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseRsvrC<M extends BaseRsvrC<M>> extends Model<M> implements IBean {

	public M setSTCD(java.lang.String STCD) {
		set("STCD", STCD);
		return (M)this;
	}
	
	public java.lang.String getSTCD() {
		return getStr("STCD");
	}

	public M setTAGF(java.lang.Integer TAGF) {
		set("TAGF", TAGF);
		return (M)this;
	}
	
	public java.lang.Integer getTAGF() {
		return getInt("TAGF");
	}

	public M setTAGT(java.lang.Integer TAGT) {
		set("TAGT", TAGT);
		return (M)this;
	}
	
	public java.lang.Integer getTAGT() {
		return getInt("TAGT");
	}

}
