package model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseParaM<M extends BaseParaM<M>> extends Model<M> implements IBean {

	public M setID(java.lang.String ID) {
		set("ID", ID);
		return (M)this;
	}
	
	public java.lang.String getID() {
		return getStr("ID");
	}

	public M setPARANAME(java.lang.String PARANAME) {
		set("PARANAME", PARANAME);
		return (M)this;
	}
	
	public java.lang.String getPARANAME() {
		return getStr("PARANAME");
	}

	public M setPARADES(java.lang.String PARADES) {
		set("PARADES", PARADES);
		return (M)this;
	}
	
	public java.lang.String getPARADES() {
		return getStr("PARADES");
	}

	public M setPARAVAL(java.math.BigDecimal PARAVAL) {
		set("PARAVAL", PARAVAL);
		return (M)this;
	}
	
	public java.math.BigDecimal getPARAVAL() {
		return get("PARAVAL");
	}

}
