package model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseUhB<M extends BaseUhB<M>> extends Model<M> implements IBean {

	public M setDMCD(java.lang.String DMCD) {
		set("DMCD", DMCD);
		return (M)this;
	}
	
	public java.lang.String getDMCD() {
		return getStr("DMCD");
	}

	public M setUHT(java.lang.Integer UHT) {
		set("UHT", UHT);
		return (M)this;
	}
	
	public java.lang.Integer getUHT() {
		return getInt("UHT");
	}

	public M setUHL(java.lang.Integer UHL) {
		set("UHL", UHL);
		return (M)this;
	}
	
	public java.lang.Integer getUHL() {
		return getInt("UHL");
	}

	public M setUH(java.math.BigDecimal UH) {
		set("UH", UH);
		return (M)this;
	}
	
	public java.math.BigDecimal getUH() {
		return get("UH");
	}

}
