package model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseMMusk<M extends BaseMMusk<M>> extends Model<M> implements IBean {

	public M setDMCD(java.lang.String DMCD) {
		set("DMCD", DMCD);
		return (M)this;
	}
	
	public java.lang.String getDMCD() {
		return getStr("DMCD");
	}

	public M setSCD(java.lang.String SCD) {
		set("SCD", SCD);
		return (M)this;
	}
	
	public java.lang.String getSCD() {
		return getStr("SCD");
	}

	public M setK(java.lang.Integer K) {
		set("K", K);
		return (M)this;
	}
	
	public java.lang.Integer getK() {
		return getInt("K");
	}

	public M setX(java.math.BigDecimal X) {
		set("X", X);
		return (M)this;
	}
	
	public java.math.BigDecimal getX() {
		return get("X");
	}

	public M setN(java.lang.Integer N) {
		set("N", N);
		return (M)this;
	}
	
	public java.lang.Integer getN() {
		return getInt("N");
	}

}
