package model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseRfnlHr<M extends BaseRfnlHr<M>> extends Model<M> implements IBean {

	public M setNO(java.lang.String NO) {
		set("NO", NO);
		return (M)this;
	}
	
	public java.lang.String getNO() {
		return getStr("NO");
	}

	public M setYMDHM(java.util.Date YMDHM) {
		set("YMDHM", YMDHM);
		return (M)this;
	}
	
	public java.util.Date getYMDHM() {
		return get("YMDHM");
	}

	public M setDBCD(java.lang.String DBCD) {
		set("DBCD", DBCD);
		return (M)this;
	}
	
	public java.lang.String getDBCD() {
		return getStr("DBCD");
	}

	public M setDMCD(java.lang.String DMCD) {
		set("DMCD", DMCD);
		return (M)this;
	}
	
	public java.lang.String getDMCD() {
		return getStr("DMCD");
	}

	public M setYMC(java.lang.Integer YMC) {
		set("YMC", YMC);
		return (M)this;
	}
	
	public java.lang.Integer getYMC() {
		return getInt("YMC");
	}

	public M setQ(java.math.BigDecimal Q) {
		set("Q", Q);
		return (M)this;
	}
	
	public java.math.BigDecimal getQ() {
		return get("Q");
	}

}
