package model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseParaMu<M extends BaseParaMu<M>> extends Model<M> implements IBean {

	public M setSTCD(java.lang.String STCD) {
		set("STCD", STCD);
		return (M)this;
	}
	
	public java.lang.String getSTCD() {
		return getStr("STCD");
	}

	public M setDBCD(java.lang.String DBCD) {
		set("DBCD", DBCD);
		return (M)this;
	}
	
	public java.lang.String getDBCD() {
		return getStr("DBCD");
	}

	public M setX(java.math.BigDecimal X) {
		set("X", X);
		return (M)this;
	}
	
	public java.math.BigDecimal getX() {
		return get("X");
	}

	public M setN(java.lang.Integer N) {
		set("N", N);
		return (M)this;
	}
	
	public java.lang.Integer getN() {
		return getInt("N");
	}

	public M setK(java.lang.Integer K) {
		set("K", K);
		return (M)this;
	}
	
	public java.lang.Integer getK() {
		return getInt("K");
	}

}
