package model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseXlqxB<M extends BaseXlqxB<M>> extends Model<M> implements IBean {

	public M setDBCD(java.lang.String DBCD) {
		set("DBCD", DBCD);
		return (M)this;
	}
	
	public java.lang.String getDBCD() {
		return getStr("DBCD");
	}

	public M setZ(java.math.BigDecimal Z) {
		set("Z", Z);
		return (M)this;
	}
	
	public java.math.BigDecimal getZ() {
		return get("Z");
	}

	public M setSTCD(java.lang.String STCD) {
		set("STCD", STCD);
		return (M)this;
	}
	
	public java.lang.String getSTCD() {
		return getStr("STCD");
	}

	public M setSFTQ(java.math.BigDecimal SFTQ) {
		set("SFTQ", SFTQ);
		return (M)this;
	}
	
	public java.math.BigDecimal getSFTQ() {
		return get("SFTQ");
	}

}
