package model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseMaterialC<M extends BaseMaterialC<M>> extends Model<M> implements IBean {

	public M setARCD(java.lang.String ARCD) {
		set("ARCD", ARCD);
		return (M)this;
	}
	
	public java.lang.String getARCD() {
		return getStr("ARCD");
	}

	public M setNO(java.lang.String NO) {
		set("NO", NO);
		return (M)this;
	}
	
	public java.lang.String getNO() {
		return getStr("NO");
	}

	public M setRNO(java.lang.Integer RNO) {
		set("RNO", RNO);
		return (M)this;
	}
	
	public java.lang.Integer getRNO() {
		return getInt("RNO");
	}

	public M setLACK(java.lang.Integer LACK) {
		set("LACK", LACK);
		return (M)this;
	}
	
	public java.lang.Integer getLACK() {
		return getInt("LACK");
	}

	public M setLACKNAME(java.lang.String LACKNAME) {
		set("LACKNAME", LACKNAME);
		return (M)this;
	}
	
	public java.lang.String getLACKNAME() {
		return getStr("LACKNAME");
	}

}
