package model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseRole<M extends BaseRole<M>> extends Model<M> implements IBean {

	public M setROLE(java.lang.Integer ROLE) {
		set("ROLE", ROLE);
		return (M)this;
	}
	
	public java.lang.Integer getROLE() {
		return getInt("ROLE");
	}

	public M setROLENM(java.lang.String ROLENM) {
		set("ROLENM", ROLENM);
		return (M)this;
	}
	
	public java.lang.String getROLENM() {
		return getStr("ROLENM");
	}

}
