package model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseForecastXajr<M extends BaseForecastXajr<M>> extends Model<M> implements IBean {

	public M setNO(java.lang.String NO) {
		set("NO", NO);
		return (M)this;
	}
	
	public java.lang.String getNO() {
		return getStr("NO");
	}

	public M setDMCD(java.lang.String DMCD) {
		set("DMCD", DMCD);
		return (M)this;
	}
	
	public java.lang.String getDMCD() {
		return getStr("DMCD");
	}

	public M setYMDHM(java.util.Date YMDHM) {
		set("YMDHM", YMDHM);
		return (M)this;
	}
	
	public java.util.Date getYMDHM() {
		return get("YMDHM");
	}

	public M setYMC(java.lang.Integer YMC) {
		set("YMC", YMC);
		return (M)this;
	}
	
	public java.lang.Integer getYMC() {
		return getInt("YMC");
	}

	public M setDRN(java.math.BigDecimal DRN) {
		set("DRN", DRN);
		return (M)this;
	}
	
	public java.math.BigDecimal getDRN() {
		return get("DRN");
	}

	public M setW(java.math.BigDecimal W) {
		set("W", W);
		return (M)this;
	}
	
	public java.math.BigDecimal getW() {
		return get("W");
	}

	public M setRR(java.math.BigDecimal RR) {
		set("RR", RR);
		return (M)this;
	}
	
	public java.math.BigDecimal getRR() {
		return get("RR");
	}

	public M setINQ(java.math.BigDecimal INQ) {
		set("INQ", INQ);
		return (M)this;
	}
	
	public java.math.BigDecimal getINQ() {
		return get("INQ");
	}

	public M setPPQ(java.math.BigDecimal PPQ) {
		set("PPQ", PPQ);
		return (M)this;
	}
	
	public java.math.BigDecimal getPPQ() {
		return get("PPQ");
	}

	public M setQ(java.math.BigDecimal Q) {
		set("Q", Q);
		return (M)this;
	}
	
	public java.math.BigDecimal getQ() {
		return get("Q");
	}

	public M setPQ(java.math.BigDecimal PQ) {
		set("PQ", PQ);
		return (M)this;
	}
	
	public java.math.BigDecimal getPQ() {
		return get("PQ");
	}

}
