package model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseDatasLt<M extends BaseDatasLt<M>> extends Model<M> implements IBean {

	public M setTYP(java.lang.Integer TYP) {
		set("TYP", TYP);
		return (M)this;
	}
	
	public java.lang.Integer getTYP() {
		return getInt("TYP");
	}

	public M setTYN(java.lang.String TYN) {
		set("TYN", TYN);
		return (M)this;
	}
	
	public java.lang.String getTYN() {
		return getStr("TYN");
	}

}
