package model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseTree<M extends BaseTree<M>> extends Model<M> implements IBean {

	public M setID(java.lang.String ID) {
		set("ID", ID);
		return (M)this;
	}
	
	public java.lang.String getID() {
		return getStr("ID");
	}

	public M setPID(java.lang.String PID) {
		set("PID", PID);
		return (M)this;
	}
	
	public java.lang.String getPID() {
		return getStr("PID");
	}

	public M setNAME(java.lang.String NAME) {
		set("NAME", NAME);
		return (M)this;
	}
	
	public java.lang.String getNAME() {
		return getStr("NAME");
	}

	public M setRANK(java.lang.Integer RANK) {
		set("RANK", RANK);
		return (M)this;
	}
	
	public java.lang.Integer getRANK() {
		return getInt("RANK");
	}

}
