package model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseViewS<M extends BaseViewS<M>> extends Model<M> implements IBean {

	public M setCODE(java.lang.Integer CODE) {
		set("CODE", CODE);
		return (M)this;
	}
	
	public java.lang.Integer getCODE() {
		return getInt("CODE");
	}

	public M setCODEN(java.lang.String CODEN) {
		set("CODEN", CODEN);
		return (M)this;
	}
	
	public java.lang.String getCODEN() {
		return getStr("CODEN");
	}

	public M setVALUE(java.lang.String VALUE) {
		set("VALUE", VALUE);
		return (M)this;
	}
	
	public java.lang.String getVALUE() {
		return getStr("VALUE");
	}

	public M setFRONTCOLORCODE(java.lang.String FRONTCOLORCODE) {
		set("FRONTCOLORCODE", FRONTCOLORCODE);
		return (M)this;
	}
	
	public java.lang.String getFRONTCOLORCODE() {
		return getStr("FRONTCOLORCODE");
	}

	public M setBACKCOLORCODE(java.lang.String BACKCOLORCODE) {
		set("BACKCOLORCODE", BACKCOLORCODE);
		return (M)this;
	}
	
	public java.lang.String getBACKCOLORCODE() {
		return getStr("BACKCOLORCODE");
	}

	public M setFONT(java.lang.String FONT) {
		set("FONT", FONT);
		return (M)this;
	}
	
	public java.lang.String getFONT() {
		return getStr("FONT");
	}

	public M setDEFAULT(java.lang.Integer DEFAULT) {
		set("DEFAULT", DEFAULT);
		return (M)this;
	}
	
	public java.lang.Integer getDEFAULT() {
		return getInt("DEFAULT");
	}

	public M setUCODE(java.lang.String UCODE) {
		set("UCODE", UCODE);
		return (M)this;
	}
	
	public java.lang.String getUCODE() {
		return getStr("UCODE");
	}

}
