package model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseAreaDis<M extends BaseAreaDis<M>> extends Model<M> implements IBean {

	public M setID(java.lang.String ID) {
		set("ID", ID);
		return (M)this;
	}
	
	public java.lang.String getID() {
		return getStr("ID");
	}

	public M setBSNM(java.lang.String BSNM) {
		set("BSNM", BSNM);
		return (M)this;
	}
	
	public java.lang.String getBSNM() {
		return getStr("BSNM");
	}

	public M setDRNA(java.math.BigDecimal DRNA) {
		set("DRNA", DRNA);
		return (M)this;
	}
	
	public java.math.BigDecimal getDRNA() {
		return get("DRNA");
	}

}
