package model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseDatasU<M extends BaseDatasU<M>> extends Model<M> implements IBean {

	public M setID(java.lang.String ID) {
		set("ID", ID);
		return (M)this;
	}
	
	public java.lang.String getID() {
		return getStr("ID");
	}

	public M setTN(java.lang.String TN) {
		set("TN", TN);
		return (M)this;
	}
	
	public java.lang.String getTN() {
		return getStr("TN");
	}

	public M setADR(java.lang.String ADR) {
		set("ADR", ADR);
		return (M)this;
	}
	
	public java.lang.String getADR() {
		return getStr("ADR");
	}

}
