package model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseRiverH<M extends BaseRiverH<M>> extends Model<M> implements IBean {

	public M setSTCD(java.lang.String STCD) {
		set("STCD", STCD);
		return (M)this;
	}
	
	public java.lang.String getSTCD() {
		return getStr("STCD");
	}

	public M setYMDHM(java.util.Date YMDHM) {
		set("YMDHM", YMDHM);
		return (M)this;
	}
	
	public java.util.Date getYMDHM() {
		return get("YMDHM");
	}

	public M setYMC(java.lang.Integer YMC) {
		set("YMC", YMC);
		return (M)this;
	}
	
	public java.lang.Integer getYMC() {
		return getInt("YMC");
	}

	public M setZ(java.math.BigDecimal Z) {
		set("Z", Z);
		return (M)this;
	}
	
	public java.math.BigDecimal getZ() {
		return get("Z");
	}

	public M setQ(java.lang.Double Q) {
		set("Q", Q);
		return (M)this;
	}
	
	public java.lang.Double getQ() {
		return getDouble("Q");
	}

}
