package model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseForecastJyt<M extends BaseForecastJyt<M>> extends Model<M> implements IBean {

	public M setNO(java.lang.String NO) {
		set("NO", NO);
		return (M)this;
	}
	
	public java.lang.String getNO() {
		return getStr("NO");
	}

	public M setID(java.lang.String ID) {
		set("ID", ID);
		return (M)this;
	}
	
	public java.lang.String getID() {
		return getStr("ID");
	}

	public M setP(java.math.BigDecimal P) {
		set("P", P);
		return (M)this;
	}
	
	public java.math.BigDecimal getP() {
		return get("P");
	}

	public M setW(java.math.BigDecimal W) {
		set("W", W);
		return (M)this;
	}
	
	public java.math.BigDecimal getW() {
		return get("W");
	}

	public M setOBW(java.math.BigDecimal OBW) {
		set("OBW", OBW);
		return (M)this;
	}
	
	public java.math.BigDecimal getOBW() {
		return get("OBW");
	}

	public M setPOW(java.math.BigDecimal POW) {
		set("POW", POW);
		return (M)this;
	}
	
	public java.math.BigDecimal getPOW() {
		return get("POW");
	}

	public M setWPE(java.math.BigDecimal WPE) {
		set("WPE", WPE);
		return (M)this;
	}
	
	public java.math.BigDecimal getWPE() {
		return get("WPE");
	}

	public M setOBPD(java.math.BigDecimal OBPD) {
		set("OBPD", OBPD);
		return (M)this;
	}
	
	public java.math.BigDecimal getOBPD() {
		return get("OBPD");
	}

	public M setFOPD(java.math.BigDecimal FOPD) {
		set("FOPD", FOPD);
		return (M)this;
	}
	
	public java.math.BigDecimal getFOPD() {
		return get("FOPD");
	}

	public M setPDE(java.math.BigDecimal PDE) {
		set("PDE", PDE);
		return (M)this;
	}
	
	public java.math.BigDecimal getPDE() {
		return get("PDE");
	}

	public M setOBPT(java.util.Date OBPT) {
		set("OBPT", OBPT);
		return (M)this;
	}
	
	public java.util.Date getOBPT() {
		return get("OBPT");
	}

	public M setFOPT(java.util.Date FOPT) {
		set("FOPT", FOPT);
		return (M)this;
	}
	
	public java.util.Date getFOPT() {
		return get("FOPT");
	}

	public M setDY(java.math.BigDecimal DY) {
		set("DY", DY);
		return (M)this;
	}
	
	public java.math.BigDecimal getDY() {
		return get("DY");
	}

}
