package model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseDayrnflCh<M extends BaseDayrnflCh<M>> extends Model<M> implements IBean {

	public M setARCD(java.lang.String ARCD) {
		set("ARCD", ARCD);
		return (M)this;
	}
	
	public java.lang.String getARCD() {
		return getStr("ARCD");
	}

	public M setNO(java.lang.String NO) {
		set("NO", NO);
		return (M)this;
	}
	
	public java.lang.String getNO() {
		return getStr("NO");
	}

	public M setAMRN(java.math.BigDecimal AMRN) {
		set("AMRN", AMRN);
		return (M)this;
	}
	
	public java.math.BigDecimal getAMRN() {
		return get("AMRN");
	}

	public M setSTMRN(java.math.BigDecimal STMRN) {
		set("STMRN", STMRN);
		return (M)this;
	}
	
	public java.math.BigDecimal getSTMRN() {
		return get("STMRN");
	}

	public M setSTCD(java.lang.String STCD) {
		set("STCD", STCD);
		return (M)this;
	}
	
	public java.lang.String getSTCD() {
		return getStr("STCD");
	}

	public M setSTNM(java.lang.String STNM) {
		set("STNM", STNM);
		return (M)this;
	}
	
	public java.lang.String getSTNM() {
		return getStr("STNM");
	}

}
