package model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseRpR<M extends BaseRpR<M>> extends Model<M> implements IBean {

	public M setARCD(java.lang.String ARCD) {
		set("ARCD", ARCD);
		return (M)this;
	}
	
	public java.lang.String getARCD() {
		return getStr("ARCD");
	}

	public M setNO(java.lang.String NO) {
		set("NO", NO);
		return (M)this;
	}
	
	public java.lang.String getNO() {
		return getStr("NO");
	}

	public M setR(java.math.BigDecimal R) {
		set("R", R);
		return (M)this;
	}
	
	public java.math.BigDecimal getR() {
		return get("R");
	}

	public M setW(java.math.BigDecimal W) {
		set("W", W);
		return (M)this;
	}
	
	public java.math.BigDecimal getW() {
		return get("W");
	}

}
