package model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseDataC<M extends BaseDataC<M>> extends Model<M> implements IBean {

	public M setIP(java.lang.Integer IP) {
		set("IP", IP);
		return (M)this;
	}
	
	public java.lang.Integer getIP() {
		return getInt("IP");
	}

	public M setIPN(java.lang.String IPN) {
		set("IPN", IPN);
		return (M)this;
	}
	
	public java.lang.String getIPN() {
		return getStr("IPN");
	}

}
