package model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseCurveHs<M extends BaseCurveHs<M>> extends Model<M> implements IBean {

	public M setDBCD(java.lang.String DBCD) {
		set("DBCD", DBCD);
		return (M)this;
	}
	
	public java.lang.String getDBCD() {
		return getStr("DBCD");
	}

	public M setZ(java.math.BigDecimal Z) {
		set("Z", Z);
		return (M)this;
	}
	
	public java.math.BigDecimal getZ() {
		return get("Z");
	}

	public M setHST(java.lang.Integer HST) {
		set("HST", HST);
		return (M)this;
	}
	
	public java.lang.Integer getHST() {
		return getInt("HST");
	}

	public M setHSTN(java.lang.String HSTN) {
		set("HSTN", HSTN);
		return (M)this;
	}
	
	public java.lang.String getHSTN() {
		return getStr("HSTN");
	}

	public M setS(java.math.BigDecimal S) {
		set("S", S);
		return (M)this;
	}
	
	public java.math.BigDecimal getS() {
		return get("S");
	}

}
