package model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseStDis<M extends BaseStDis<M>> extends Model<M> implements IBean {

	public M setSTCD(java.lang.String STCD) {
		set("STCD", STCD);
		return (M)this;
	}
	
	public java.lang.String getSTCD() {
		return getStr("STCD");
	}

	public M setSTNM(java.lang.String STNM) {
		set("STNM", STNM);
		return (M)this;
	}
	
	public java.lang.String getSTNM() {
		return getStr("STNM");
	}

	public M setRVNM(java.lang.String RVNM) {
		set("RVNM", RVNM);
		return (M)this;
	}
	
	public java.lang.String getRVNM() {
		return getStr("RVNM");
	}

	public M setHNNM(java.lang.String HNNM) {
		set("HNNM", HNNM);
		return (M)this;
	}
	
	public java.lang.String getHNNM() {
		return getStr("HNNM");
	}

	public M setBSNM(java.lang.String BSNM) {
		set("BSNM", BSNM);
		return (M)this;
	}
	
	public java.lang.String getBSNM() {
		return getStr("BSNM");
	}

	public M setLGTD(java.lang.String LGTD) {
		set("LGTD", LGTD);
		return (M)this;
	}
	
	public java.lang.String getLGTD() {
		return getStr("LGTD");
	}

	public M setLTTD(java.lang.String LTTD) {
		set("LTTD", LTTD);
		return (M)this;
	}
	
	public java.lang.String getLTTD() {
		return getStr("LTTD");
	}

	public M setSTLC(java.lang.String STLC) {
		set("STLC", STLC);
		return (M)this;
	}
	
	public java.lang.String getSTLC() {
		return getStr("STLC");
	}

	public M setADDVCD(java.lang.String ADDVCD) {
		set("ADDVCD", ADDVCD);
		return (M)this;
	}
	
	public java.lang.String getADDVCD() {
		return getStr("ADDVCD");
	}

	public M setMDBZ(java.math.BigDecimal MDBZ) {
		set("MDBZ", MDBZ);
		return (M)this;
	}
	
	public java.math.BigDecimal getMDBZ() {
		return get("MDBZ");
	}

	public M setMDPR(java.math.BigDecimal MDPR) {
		set("MDPR", MDPR);
		return (M)this;
	}
	
	public java.math.BigDecimal getMDPR() {
		return get("MDPR");
	}

	public M setDTMNM(java.lang.String DTMNM) {
		set("DTMNM", DTMNM);
		return (M)this;
	}
	
	public java.lang.String getDTMNM() {
		return getStr("DTMNM");
	}

	public M setDTMEL(java.math.BigDecimal DTMEL) {
		set("DTMEL", DTMEL);
		return (M)this;
	}
	
	public java.math.BigDecimal getDTMEL() {
		return get("DTMEL");
	}

	public M setSTTP(java.lang.String STTP) {
		set("STTP", STTP);
		return (M)this;
	}
	
	public java.lang.String getSTTP() {
		return getStr("STTP");
	}

	public M setDFRTMS(java.math.BigDecimal DFRTMS) {
		set("DFRTMS", DFRTMS);
		return (M)this;
	}
	
	public java.math.BigDecimal getDFRTMS() {
		return get("DFRTMS");
	}

	public M setFRITM(java.lang.String FRITM) {
		set("FRITM", FRITM);
		return (M)this;
	}
	
	public java.lang.String getFRITM() {
		return getStr("FRITM");
	}

	public M setFRGRD(java.lang.String FRGRD) {
		set("FRGRD", FRGRD);
		return (M)this;
	}
	
	public java.lang.String getFRGRD() {
		return getStr("FRGRD");
	}

	public M setBGFRYM(java.lang.String BGFRYM) {
		set("BGFRYM", BGFRYM);
		return (M)this;
	}
	
	public java.lang.String getBGFRYM() {
		return getStr("BGFRYM");
	}

	public M setEDFRYM(java.lang.String EDFRYM) {
		set("EDFRYM", EDFRYM);
		return (M)this;
	}
	
	public java.lang.String getEDFRYM() {
		return getStr("EDFRYM");
	}

	public M setADMAUTH(java.lang.String ADMAUTH) {
		set("ADMAUTH", ADMAUTH);
		return (M)this;
	}
	
	public java.lang.String getADMAUTH() {
		return getStr("ADMAUTH");
	}

	public M setSTBK(java.lang.String STBK) {
		set("STBK", STBK);
		return (M)this;
	}
	
	public java.lang.String getSTBK() {
		return getStr("STBK");
	}

	public M setDRNA(java.math.BigDecimal DRNA) {
		set("DRNA", DRNA);
		return (M)this;
	}
	
	public java.math.BigDecimal getDRNA() {
		return get("DRNA");
	}

	public M setPHCD(java.lang.String PHCD) {
		set("PHCD", PHCD);
		return (M)this;
	}
	
	public java.lang.String getPHCD() {
		return getStr("PHCD");
	}

}
