package model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseEventFe<M extends BaseEventFe<M>> extends Model<M> implements IBean {

	public M setID(java.lang.String ID) {
		set("ID", ID);
		return (M)this;
	}
	
	public java.lang.String getID() {
		return getStr("ID");
	}

	public M setSTARTTM(java.util.Date STARTTM) {
		set("STARTTM", STARTTM);
		return (M)this;
	}
	
	public java.util.Date getSTARTTM() {
		return get("STARTTM");
	}

	public M setENDTM(java.util.Date ENDTM) {
		set("ENDTM", ENDTM);
		return (M)this;
	}
	
	public java.util.Date getENDTM() {
		return get("ENDTM");
	}

	public M setYMC2(java.lang.Integer YMC2) {
		set("YMC2", YMC2);
		return (M)this;
	}
	
	public java.lang.Integer getYMC2() {
		return getInt("YMC2");
	}

	public M setYMC3(java.lang.Integer YMC3) {
		set("YMC3", YMC3);
		return (M)this;
	}
	
	public java.lang.Integer getYMC3() {
		return getInt("YMC3");
	}

	public M setOK(java.lang.String OK) {
		set("OK", OK);
		return (M)this;
	}
	
	public java.lang.String getOK() {
		return getStr("OK");
	}

}
