package model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseTqR<M extends BaseTqR<M>> extends Model<M> implements IBean {

	public M setNO(java.lang.String NO) {
		set("NO", NO);
		return (M)this;
	}
	
	public java.lang.String getNO() {
		return getStr("NO");
	}

	public M setYMDHM(java.util.Date YMDHM) {
		set("YMDHM", YMDHM);
		return (M)this;
	}
	
	public java.util.Date getYMDHM() {
		return get("YMDHM");
	}

	public M setDBCD(java.lang.String DBCD) {
		set("DBCD", DBCD);
		return (M)this;
	}
	
	public java.lang.String getDBCD() {
		return getStr("DBCD");
	}

	public M setYMC(java.lang.Integer YMC) {
		set("YMC", YMC);
		return (M)this;
	}
	
	public java.lang.Integer getYMC() {
		return getInt("YMC");
	}

	public M setOTQ(java.math.BigDecimal OTQ) {
		set("OTQ", OTQ);
		return (M)this;
	}
	
	public java.math.BigDecimal getOTQ() {
		return get("OTQ");
	}

	public M setTQ(java.math.BigDecimal TQ) {
		set("TQ", TQ);
		return (M)this;
	}
	
	public java.math.BigDecimal getTQ() {
		return get("TQ");
	}

}
