package model.baseoracle;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseDayevR<M extends BaseDayevR<M>> extends Model<M> implements IBean {

	public M setStcd(java.lang.String stcd) {
		set("STCD", stcd);
		return (M)this;
	}
	
	public java.lang.String getStcd() {
		return getStr("STCD");
	}

	public M setTm(java.util.Date tm) {
		set("TM", tm);
		return (M)this;
	}
	
	public java.util.Date getTm() {
		return get("TM");
	}

	public M setEptp(java.lang.String eptp) {
		set("EPTP", eptp);
		return (M)this;
	}
	
	public java.lang.String getEptp() {
		return getStr("EPTP");
	}

	public M setDye(java.math.BigDecimal dye) {
		set("DYE", dye);
		return (M)this;
	}
	
	public java.math.BigDecimal getDye() {
		return get("DYE");
	}

}
