package model.baseoracle;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BasePptnR<M extends BasePptnR<M>> extends Model<M> implements IBean {

	public M setStcd(java.lang.String stcd) {
		set("STCD", stcd);
		return (M)this;
	}
	
	public java.lang.String getStcd() {
		return getStr("STCD");
	}

	public M setTm(java.util.Date tm) {
		set("TM", tm);
		return (M)this;
	}
	
	public java.util.Date getTm() {
		return get("TM");
	}

	public M setDrp(java.math.BigDecimal drp) {
		set("DRP", drp);
		return (M)this;
	}
	
	public java.math.BigDecimal getDrp() {
		return get("DRP");
	}

	public M setIntv(java.math.BigDecimal intv) {
		set("INTV", intv);
		return (M)this;
	}
	
	public java.math.BigDecimal getIntv() {
		return get("INTV");
	}

	public M setPdr(java.math.BigDecimal pdr) {
		set("PDR", pdr);
		return (M)this;
	}
	
	public java.math.BigDecimal getPdr() {
		return get("PDR");
	}

	public M setDyp(java.math.BigDecimal dyp) {
		set("DYP", dyp);
		return (M)this;
	}
	
	public java.math.BigDecimal getDyp() {
		return get("DYP");
	}

	public M setWth(java.lang.String wth) {
		set("WTH", wth);
		return (M)this;
	}
	
	public java.lang.String getWth() {
		return getStr("WTH");
	}

}
