package model.baseoracle;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseForecastcF<M extends BaseForecastcF<M>> extends Model<M> implements IBean {

	public M setStcd(java.lang.String stcd) {
		set("STCD", stcd);
		return (M)this;
	}
	
	public java.lang.String getStcd() {
		return getStr("STCD");
	}

	public M setUnitnmae(java.lang.String unitnmae) {
		set("UNITNMAE", unitnmae);
		return (M)this;
	}
	
	public java.lang.String getUnitnmae() {
		return getStr("UNITNMAE");
	}

	public M setPlcd(java.lang.String plcd) {
		set("PLCD", plcd);
		return (M)this;
	}
	
	public java.lang.String getPlcd() {
		return getStr("PLCD");
	}

	public M setFymdh(java.util.Date fymdh) {
		set("FYMDH", fymdh);
		return (M)this;
	}
	
	public java.util.Date getFymdh() {
		return get("FYMDH");
	}

	public M setIymdh(java.util.Date iymdh) {
		set("IYMDH", iymdh);
		return (M)this;
	}
	
	public java.util.Date getIymdh() {
		return get("IYMDH");
	}

	public M setWnstatus(java.lang.String wnstatus) {
		set("WNSTATUS", wnstatus);
		return (M)this;
	}
	
	public java.lang.String getWnstatus() {
		return getStr("WNSTATUS");
	}

	public M setComments(java.lang.String comments) {
		set("COMMENTS", comments);
		return (M)this;
	}
	
	public java.lang.String getComments() {
		return getStr("COMMENTS");
	}

	public M setKssj(java.util.Date kssj) {
		set("KSSJ", kssj);
		return (M)this;
	}
	
	public java.util.Date getKssj() {
		return get("KSSJ");
	}

	public M setLx(java.lang.String lx) {
		set("LX", lx);
		return (M)this;
	}
	
	public java.lang.String getLx() {
		return getStr("LX");
	}

}
