package model.baseoracle;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseRvavR<M extends BaseRvavR<M>> extends Model<M> implements IBean {

	public M setStcd(java.lang.String stcd) {
		set("STCD", stcd);
		return (M)this;
	}
	
	public java.lang.String getStcd() {
		return getStr("STCD");
	}

	public M setIdtm(java.util.Date idtm) {
		set("IDTM", idtm);
		return (M)this;
	}
	
	public java.util.Date getIdtm() {
		return get("IDTM");
	}

	public M setSttdrcd(java.lang.String sttdrcd) {
		set("STTDRCD", sttdrcd);
		return (M)this;
	}
	
	public java.lang.String getSttdrcd() {
		return getStr("STTDRCD");
	}

	public M setAvz(java.math.BigDecimal avz) {
		set("AVZ", avz);
		return (M)this;
	}
	
	public java.math.BigDecimal getAvz() {
		return get("AVZ");
	}

	public M setAvq(java.math.BigDecimal avq) {
		set("AVQ", avq);
		return (M)this;
	}
	
	public java.math.BigDecimal getAvq() {
		return get("AVQ");
	}

}
