package model.baseoracle;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseRiverR<M extends BaseRiverR<M>> extends Model<M> implements IBean {

	public M setStcd(java.lang.String stcd) {
		set("STCD", stcd);
		return (M)this;
	}
	
	public java.lang.String getStcd() {
		return getStr("STCD");
	}

	public M setTm(java.util.Date tm) {
		set("TM", tm);
		return (M)this;
	}
	
	public java.util.Date getTm() {
		return get("TM");
	}

	public M setZ(java.math.BigDecimal z) {
		set("Z", z);
		return (M)this;
	}
	
	public java.math.BigDecimal getZ() {
		return get("Z");
	}

	public M setQ(java.math.BigDecimal q) {
		set("Q", q);
		return (M)this;
	}
	
	public java.math.BigDecimal getQ() {
		return get("Q");
	}

	public M setXsa(java.math.BigDecimal xsa) {
		set("XSA", xsa);
		return (M)this;
	}
	
	public java.math.BigDecimal getXsa() {
		return get("XSA");
	}

	public M setXsavv(java.math.BigDecimal xsavv) {
		set("XSAVV", xsavv);
		return (M)this;
	}
	
	public java.math.BigDecimal getXsavv() {
		return get("XSAVV");
	}

	public M setXsmxv(java.math.BigDecimal xsmxv) {
		set("XSMXV", xsmxv);
		return (M)this;
	}
	
	public java.math.BigDecimal getXsmxv() {
		return get("XSMXV");
	}

	public M setFlwchrcd(java.lang.String flwchrcd) {
		set("FLWCHRCD", flwchrcd);
		return (M)this;
	}
	
	public java.lang.String getFlwchrcd() {
		return getStr("FLWCHRCD");
	}

	public M setWptn(java.lang.String wptn) {
		set("WPTN", wptn);
		return (M)this;
	}
	
	public java.lang.String getWptn() {
		return getStr("WPTN");
	}

	public M setMsqmt(java.lang.String msqmt) {
		set("MSQMT", msqmt);
		return (M)this;
	}
	
	public java.lang.String getMsqmt() {
		return getStr("MSQMT");
	}

	public M setMsamt(java.lang.String msamt) {
		set("MSAMT", msamt);
		return (M)this;
	}
	
	public java.lang.String getMsamt() {
		return getStr("MSAMT");
	}

	public M setMsvmt(java.lang.String msvmt) {
		set("MSVMT", msvmt);
		return (M)this;
	}
	
	public java.lang.String getMsvmt() {
		return getStr("MSVMT");
	}

}
