package model.dbmodeloracle;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {
	
	public static void mapping(ActiveRecordPlugin arp) {
		// Composite Primary Key order: STCD,TM
		arp.addMapping("ST_DAYEV_R", "STCD,TM", DayevR.class);
		// Composite Primary Key order: FYMDH,IYMDH,PLCD,STCD,UNITNMAE
		arp.addMapping("ST_FORECASTC_F", "FYMDH,IYMDH,PLCD,STCD,UNITNMAE", ForecastcF.class);
		// Composite Primary Key order: FYMDH,IYMDH,PLCD,STCD,UNITNAME,YMDH
		arp.addMapping("ST_FORECAST_F", "FYMDH,IYMDH,PLCD,STCD,UNITNAME,YMDH", ForecastF.class);
		// Composite Primary Key order: EXKEY,STCD,TM
		arp.addMapping("ST_GATE_R", "EXKEY,STCD,TM", GateR.class);
		// Composite Primary Key order: STCD,TM
		arp.addMapping("ST_PPTN_R", "STCD,TM", PptnR.class);
		// Composite Primary Key order: FYMDH,IYMDH,PLCD,STCD,UNITNAME,YMDH
		arp.addMapping("ST_REGLAT_F", "FYMDH,IYMDH,PLCD,STCD,UNITNAME,YMDH", ReglatF.class);
		// Composite Primary Key order: STCD,TM
		arp.addMapping("ST_RIVER_R", "STCD,TM", RiverR.class);
		// Composite Primary Key order: IDTM,STCD,STTDRCD
		arp.addMapping("ST_RSVRAV_R", "IDTM,STCD,STTDRCD", RsvravR.class);
		// Composite Primary Key order: STCD,TM
		arp.addMapping("ST_RSVR_R", "STCD,TM", RsvrR.class);
		// Composite Primary Key order: IDTM,STCD,STTDRCD
		arp.addMapping("ST_RVAV_R", "IDTM,STCD,STTDRCD", RvavR.class);
		// Composite Primary Key order: STCD,TM
		arp.addMapping("ST_WAS_R", "STCD,TM", WasR.class);
	}
}

