package model.dbmodeloracle;

import model.baseoracle.BaseDayevR;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DayevR extends BaseDayevR<DayevR> {
	public static final DayevR dao = new DayevR().dao();
}
