package model.dbmodeloracle;

import model.baseoracle.BaseForecastcF;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ForecastcF extends BaseForecastcF<ForecastcF> {
	public static final ForecastcF dao = new ForecastcF().dao();
}
