package model.dbmodeloracle;

import model.baseoracle.BaseForecastF;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ForecastF extends BaseForecastF<ForecastF> {
	public static final ForecastF dao = new ForecastF().dao();
}
