package model.dbmodeloracle;

import model.baseoracle.BaseGateR;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class GateR extends BaseGateR<GateR> {
	public static final GateR dao = new GateR().dao();
}
