package model.dbmodeloracle;

import model.baseoracle.BasePptnR;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PptnR extends BasePptnR<PptnR> {
	public static final PptnR dao = new PptnR().dao();
}
