package model.dbmodeloracle;

import model.baseoracle.BaseReglatF;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ReglatF extends BaseReglatF<ReglatF> {
	public static final ReglatF dao = new ReglatF().dao();
}
