package model.dbmodeloracle;

import model.baseoracle.BaseRiverR;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class RiverR extends BaseRiverR<RiverR> {
	public static final RiverR dao = new RiverR().dao();
}
