package model.dbmodeloracle;

import model.baseoracle.BaseRsvrR;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class RsvrR extends BaseRsvrR<RsvrR> {
	public static final RsvrR dao = new RsvrR().dao();
}
