package model.dbmodeloracle;

import model.baseoracle.BaseRsvravR;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class RsvravR extends BaseRsvravR<RsvravR> {
	public static final RsvravR dao = new RsvravR().dao();
}
