package model.dbmodeloracle;

import model.baseoracle.BaseRvavR;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class RvavR extends BaseRvavR<RvavR> {
	public static final RvavR dao = new RvavR().dao();
}
